### PR TITLE
Add Dev lang, IDE symbols

### PR DESCRIPTION
**Pull request by jalpp**
Hey!

Creating PR to add dev lang and IDE flairs 

PR adds

Git related:
- Git

Languages:
 - Java
 - Python
 - Javascript
 - Scala
 - Typescript
 - Rust
 - Terraform
 - Nodejs
 
 Frameworks
 - React
 
 IDE
 - IntelliJ
 - Neo Vim
 - Vscode 
 
 terraform
neovim
vscode
intellij
typescript
git
react
nodejs
rust
scala
python
javascript
java

Let me know if there are any issues!

Thanks

### CODE REVIEW

**Comment by ForexPatriot77** [comment]
New suggestion ideas. Time variant logos

Screenshot_20231128_225327_Firefox
Screenshot_20231128_225345_Firefox
Screenshot_20231128_225356_Firefox

I suppose the devs could make images similar to rapid and classical, but I'm only assuming that those who play fast time controls will use flairs.

**Comment by ForexPatriot77** [comment]
1280px-Chess_Pieces_Sprite svg

Maybe some chess piece flairs would work as well

**Comment by jalpp** [comment]
sure I can add them after this one

**Comment by ornicar** [comment]
a few issues:

- they don't all have the same size
- they're not all square
- they don't all have a transparent background
- we don't have license info about them
- the flairs have moved to lila

**Pull request closed without merging**
